//! Renders the documentation model as Starlight MDX pages.
//!
//! One page per command group, each leaf command an `##` heading so
//! Starlight's table of contents doubles as a command index. Everything
//! below a heading is derived from clap; the prose that frames it lives in
//! [`OVERVIEW`] here, so the whole page is still covered by the drift check.

use crate::model::{ArgDoc, CommandDoc};

/// Marks the output as machine-written, in MDX comment syntax.
const BANNER: &str = "{/* Generated by `just docs-cli` from the tix source itself.\n    Edits made here are overwritten; change the generator under xtask/. */}";

/// Sidebar ordering for the groups we ship.
///
/// Only affects presentation: a group that is not listed still renders, and
/// sorts after the ones that are.
const GROUP_ORDER: [&str; 4] = ["ticket", "repo", "config", "cli"];

/// One rendered file.
pub struct Page {
    /// Path relative to the content root, e.g. `reference/cli/ticket.mdx`.
    pub path: String,
    pub body: String,
}

/// Renders the whole reference: an overview page plus one page per group.
pub fn render(root: &CommandDoc) -> Vec<Page> {
    let mut pages = vec![Page {
        path: "reference/cli/index.mdx".to_string(),
        body: render_overview(root),
    }];
    for group in root.subcommands.iter().filter(|sub| sub.is_group()) {
        pages.push(Page {
            path: format!("reference/cli/{}.mdx", group.name),
            body: render_group(group),
        });
    }
    pages
}

/// The overview page: how to read the reference, the flags every command
/// accepts, and an index of all fourteen leaf commands.
fn render_overview(root: &CommandDoc) -> String {
    let mut out = String::new();
    out.push_str(&frontmatter(
        "CLI Reference",
        "Every tix command and flag, generated from the CLI's own definition.",
        1,
        2,
    ));
    out.push_str(OVERVIEW);
    out.push_str("\n## Global options\n\nThese are accepted by every command, before or after the subcommand.\n\n");
    out.push_str(&arg_table("Option", &root.options));
    out.push_str("\n## Command index\n\n");
    out.push_str(&command_index(root));
    out.push_str(ENVIRONMENT);
    out
}

/// A group page: the group's own synopsis, then every leaf beneath it.
fn render_group(group: &CommandDoc) -> String {
    let order = GROUP_ORDER
        .iter()
        .position(|name| *name == group.name)
        .map(|index| index + 2)
        .unwrap_or(GROUP_ORDER.len() + 2);

    let mut out = frontmatter(
        &format!("tix {}", group.name),
        group.about.as_deref().unwrap_or("Command reference"),
        order,
        2,
    );
    if let Some(about) = &group.about {
        out.push_str(&format!("{}\n\n", escape(about)));
    }
    out.push_str(&format!("{}\n", synopsis(&group.usage)));
    for leaf in &group.subcommands {
        out.push_str(&render_command(leaf));
    }
    out
}

/// One leaf command: description, synopsis, aliases, arguments, options.
fn render_command(command: &CommandDoc) -> String {
    let mut out = format!("\n## `{}`\n\n", command.path);
    if let Some(about) = &command.about {
        out.push_str(&format!("{}\n\n", escape(about)));
    }
    out.push_str(&format!("{}\n\n", synopsis(&command.usage)));

    if !command.aliases.is_empty() {
        let spelled: Vec<String> = command
            .aliases
            .iter()
            .map(|alias| format!("`{alias}`"))
            .collect();
        out.push_str(&format!(
            "Also available as {} — the same command, spelled without the group.\n\n",
            spelled.join(" and ")
        ));
    }

    if let Some(long) = &command.long_about {
        out.push_str(&format!("{}\n\n", escape(long)));
    }
    if !command.positionals.is_empty() {
        out.push_str("### Arguments\n\n");
        out.push_str(&arg_table("Argument", &command.positionals));
        out.push('\n');
    }
    if !command.options.is_empty() {
        out.push_str("### Options\n\n");
        out.push_str(&arg_table("Option", &command.options));
        out.push('\n');
    }
    out
}

/// Renders arguments as a two-column table, folding defaults and accepted
/// values into the description rather than spending a column on each.
fn arg_table(heading: &str, args: &[ArgDoc]) -> String {
    let mut out = format!("| {heading} | Description |\n| --- | --- |\n");
    for arg in args {
        let mut description = arg
            .help
            .as_deref()
            .map(cell)
            .unwrap_or_else(|| "—".to_string());
        if !arg.possible_values.is_empty() {
            let values: Vec<String> = arg
                .possible_values
                .iter()
                .map(|value| format!("`{value}`"))
                .collect();
            description.push_str(&format!("<br />Accepts: {}", values.join(", ")));
        }
        if let Some(default) = &arg.default {
            description.push_str(&format!("<br />Default: `{default}`"));
        }
        if arg.required && !arg.invocation.starts_with('<') {
            description.push_str("<br />Required.");
        }
        out.push_str(&format!("| `{}` | {} |\n", arg.invocation, description));
    }
    out
}

/// A table of every leaf command, linking into its group page.
fn command_index(root: &CommandDoc) -> String {
    let mut out = String::from("| Command | Description |\n| --- | --- |\n");
    for group in root.subcommands.iter().filter(|sub| sub.is_group()) {
        for leaf in &group.subcommands {
            let anchor = leaf.path.replace(' ', "-");
            let mut description = leaf
                .about
                .as_deref()
                .map(cell)
                .unwrap_or_else(|| "—".to_string());
            if !leaf.aliases.is_empty() {
                let spelled: Vec<String> = leaf
                    .aliases
                    .iter()
                    .map(|alias| format!("`{alias}`"))
                    .collect();
                description.push_str(&format!("<br />Alias: {}", spelled.join(", ")));
            }
            // Relative, not absolute: the site is published under a base
            // path per version (`/dev/`, `/latest/`, `/v3.1/`), and Astro
            // rewrites the base into links it manages but not into links
            // written inside markdown. A sibling-relative href is correct at
            // every base.
            out.push_str(&format!(
                "| [`{}`](./{}/#{}) | {} |\n",
                leaf.path, group.name, anchor, description
            ));
        }
    }
    out
}

/// Starlight page frontmatter, plus the generated-file banner.
pub fn frontmatter(title: &str, description: &str, order: usize, toc_depth: usize) -> String {
    format!(
        "---\ntitle: {title}\ndescription: {description}\nsidebar:\n  order: {order}\ntableOfContents:\n  maxHeadingLevel: {toc_depth}\n---\n\n{BANNER}\n\n"
    )
}

/// A usage line as an unframed code block.
///
/// Expressive Code renders a shell block as a terminal window; a synopsis is
/// a grammar rather than a session, so that chrome misleads.
fn synopsis(usage: &str) -> String {
    format!("```sh frame=\"none\"\n{usage}\n```\n")
}

/// Escapes text taken from clap for MDX prose.
///
/// `<` would open a JSX element and `{` a JSX expression; both appear in help
/// text often enough (`<path|id>`, `{a,b}`) that leaving them raw is a build
/// failure waiting to happen.
pub fn escape(text: &str) -> String {
    // Only outside inline code. MDX does not parse JSX inside a code span, so
    // escaping there is not merely unnecessary — `<` becomes a literal
    // "&lt;" on the page.
    let mut out = String::with_capacity(text.len());
    let mut in_code = false;
    for c in text.chars() {
        match c {
            '`' => {
                in_code = !in_code;
                out.push(c);
            }
            '&' if !in_code => out.push_str("&amp;"),
            '<' if !in_code => out.push_str("&lt;"),
            '{' if !in_code => out.push_str("&#123;"),
            _ => out.push(c),
        }
    }
    out
}

/// Escapes text for a markdown table cell: as [`escape`], plus the pipe that
/// would end the cell and the newlines that would end the row.
pub fn cell(text: &str) -> String {
    escape(text)
        .replace('|', "\\|")
        .replace("\n\n", "<br /><br />")
        .replace('\n', " ")
}

/// Hand-written framing for the overview page.
///
/// Kept in the generator rather than a checked-in partial so that the drift
/// check covers the entire rendered page, not just its tables.
const OVERVIEW: &str = r#"
Every command `tix` accepts, generated from the CLI's own argument
definition.

## Notation

| Form | Meaning |
| --- | --- |
| `<VALUE>` | Required. |
| `[VALUE]` | Optional. |
| `<VALUE>...` | Repeatable. |

Every command also accepts `-h` / `--help`; `tix --version` prints the
version.

## Selecting a ticket

`tix ticket add`, `remove`, `info`, and `destroy` act on one ticket. With no
flag they discover it by walking up from the working directory for a
`.tix/ticket.toml`, nearest ancestor winning.

`--ticket` skips the walk, and its argument is read by shape:

| You write | Read as | Resolves to |
| --- | --- | --- |
| `JIRA-123` | id | `tickets_directory/JIRA-123` |
| `./JIRA-123` | path | that directory |
| `../other`, `/abs/path`, `.` | path | that directory |

A bare name is **always** an id, so a ticket in your working directory must
be written `./JIRA-123`. Both forms assert *this is a ticket root*; pointing
at a subdirectory is an error.

`tix destroy` also takes the ticket positionally, read the same two ways. It
conflicts with `--ticket`.

## Plugins

Any argument `tix` does not recognize is dispatched to a plugin: `tix deploy`
execs `tix-deploy` from `PATH` with the workspace context forwarded.
See the [plugin specification](../../plugins/specification/).
"#;

/// Environment and exit-status notes, appended to the overview.
const ENVIRONMENT: &str = r#"
## Environment

`TIX_CONFIG_PATH` sets the global config location. `--config` beats it, and
it is ignored when set but empty. With neither, the file is read from the
platform config directory — `~/.config/tix/config.toml` on Linux,
`~/Library/Application Support/tix/config.toml` on macOS. Every command
except `tix config init` and `tix cli completions` requires it to exist.

## Exit status

`0` on success, `1` on any error, with `error: <message>` on stderr.
Diagnostics and logs also go to stderr, so `tix list --output json | jq`
stays parseable at any log level.
"#;
