//! Renders the documentation model as Starlight MDX pages.
//!
//! One page per command group, each leaf command an `##` heading so
//! Starlight's table of contents doubles as a command index. Everything
//! below a heading is derived from clap; the prose that frames it lives in
//! [`OVERVIEW`] here, so the whole page is still covered by the drift check.

use crate::model::{ArgDoc, CommandDoc};

/// Marks the output as machine-written, in MDX comment syntax.
const BANNER: &str = "{/* Generated by `just docs-cli` from the clap definition in tix-cli.\n    Edit xtask/src/mdx.rs, not this file. */}";

/// Sidebar ordering for the groups we ship.
///
/// Only affects presentation: a group that is not listed still renders, and
/// sorts after the ones that are.
const GROUP_ORDER: [&str; 4] = ["ticket", "repo", "config", "cli"];

/// One rendered file.
pub struct Page {
    /// Path relative to the content root, e.g. `reference/cli/ticket.mdx`.
    pub path: String,
    pub body: String,
}

/// Renders the whole reference: an overview page plus one page per group.
pub fn render(root: &CommandDoc) -> Vec<Page> {
    let mut pages = vec![Page {
        path: "reference/cli/index.mdx".to_string(),
        body: render_overview(root),
    }];
    for group in root.subcommands.iter().filter(|sub| sub.is_group()) {
        pages.push(Page {
            path: format!("reference/cli/{}.mdx", group.name),
            body: render_group(group),
        });
    }
    pages
}

/// The overview page: how to read the reference, the flags every command
/// accepts, and an index of all fourteen leaf commands.
fn render_overview(root: &CommandDoc) -> String {
    let mut out = String::new();
    out.push_str(&frontmatter(
        "CLI reference",
        "Every tix command and flag, generated from the CLI's own definition.",
        1,
    ));
    out.push_str(OVERVIEW);
    out.push_str("\n## Global options\n\nThese are accepted by every command, before or after the subcommand.\n\n");
    out.push_str(&arg_table("Option", &root.options));
    out.push_str("\n## Command index\n\n");
    out.push_str(&command_index(root));
    out.push_str(ENVIRONMENT);
    out
}

/// A group page: the group's own synopsis, then every leaf beneath it.
fn render_group(group: &CommandDoc) -> String {
    let order = GROUP_ORDER
        .iter()
        .position(|name| *name == group.name)
        .map(|index| index + 2)
        .unwrap_or(GROUP_ORDER.len() + 2);

    let mut out = frontmatter(
        &format!("tix {}", group.name),
        group.about.as_deref().unwrap_or("Command reference"),
        order,
    );
    if let Some(about) = &group.about {
        out.push_str(&format!("{}\n\n", escape(about)));
    }
    out.push_str(&format!("{}\n", synopsis(&group.usage)));
    for leaf in &group.subcommands {
        out.push_str(&render_command(leaf));
    }
    out
}

/// One leaf command: description, synopsis, aliases, arguments, options.
fn render_command(command: &CommandDoc) -> String {
    let mut out = format!("\n## `{}`\n\n", command.path);
    if let Some(about) = &command.about {
        out.push_str(&format!("{}\n\n", escape(about)));
    }
    out.push_str(&format!("{}\n\n", synopsis(&command.usage)));

    if !command.aliases.is_empty() {
        let spelled: Vec<String> = command
            .aliases
            .iter()
            .map(|alias| format!("`{alias}`"))
            .collect();
        out.push_str(&format!(
            "Also available as {} — the same command, spelled without the group.\n\n",
            spelled.join(" and ")
        ));
    }

    if let Some(long) = &command.long_about {
        out.push_str(&format!("{}\n\n", escape(long)));
    }
    if !command.positionals.is_empty() {
        out.push_str("### Arguments\n\n");
        out.push_str(&arg_table("Argument", &command.positionals));
        out.push('\n');
    }
    if !command.options.is_empty() {
        out.push_str("### Options\n\n");
        out.push_str(&arg_table("Option", &command.options));
        out.push('\n');
    }
    out
}

/// Renders arguments as a two-column table, folding defaults and accepted
/// values into the description rather than spending a column on each.
fn arg_table(heading: &str, args: &[ArgDoc]) -> String {
    let mut out = format!("| {heading} | Description |\n| --- | --- |\n");
    for arg in args {
        let mut description = arg
            .help
            .as_deref()
            .map(cell)
            .unwrap_or_else(|| "—".to_string());
        if !arg.possible_values.is_empty() {
            let values: Vec<String> = arg
                .possible_values
                .iter()
                .map(|value| format!("`{value}`"))
                .collect();
            description.push_str(&format!("<br />Accepts: {}", values.join(", ")));
        }
        if let Some(default) = &arg.default {
            description.push_str(&format!("<br />Default: `{default}`"));
        }
        if arg.required && !arg.invocation.starts_with('<') {
            description.push_str("<br />Required.");
        }
        out.push_str(&format!("| `{}` | {} |\n", arg.invocation, description));
    }
    out
}

/// A table of every leaf command, linking into its group page.
fn command_index(root: &CommandDoc) -> String {
    let mut out = String::from("| Command | Description |\n| --- | --- |\n");
    for group in root.subcommands.iter().filter(|sub| sub.is_group()) {
        for leaf in &group.subcommands {
            let anchor = leaf.path.replace(' ', "-");
            let mut description = leaf
                .about
                .as_deref()
                .map(cell)
                .unwrap_or_else(|| "—".to_string());
            if !leaf.aliases.is_empty() {
                let spelled: Vec<String> = leaf
                    .aliases
                    .iter()
                    .map(|alias| format!("`{alias}`"))
                    .collect();
                description.push_str(&format!("<br />Alias: {}", spelled.join(", ")));
            }
            // Relative, not absolute: the site is published under a base
            // path per version (`/dev/`, `/latest/`, `/v3.1/`), and Astro
            // rewrites the base into links it manages but not into links
            // written inside markdown. A sibling-relative href is correct at
            // every base.
            out.push_str(&format!(
                "| [`{}`](./{}/#{}) | {} |\n",
                leaf.path, group.name, anchor, description
            ));
        }
    }
    out
}

/// Starlight page frontmatter, plus the generated-file banner.
fn frontmatter(title: &str, description: &str, order: usize) -> String {
    format!(
        "---\ntitle: {title}\ndescription: {description}\nsidebar:\n  order: {order}\ntableOfContents:\n  maxHeadingLevel: 2\n---\n\n{BANNER}\n\n"
    )
}

/// A usage line as an unframed code block.
///
/// Expressive Code renders a shell block as a terminal window; a synopsis is
/// a grammar rather than a session, so that chrome misleads.
fn synopsis(usage: &str) -> String {
    format!("```sh frame=\"none\"\n{usage}\n```\n")
}

/// Escapes text taken from clap for MDX prose.
///
/// `<` would open a JSX element and `{` a JSX expression; both appear in help
/// text often enough (`<path|id>`, `{a,b}`) that leaving them raw is a build
/// failure waiting to happen.
fn escape(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('{', "&#123;")
}

/// Escapes text for a markdown table cell: as [`escape`], plus the pipe that
/// would end the cell and the newlines that would end the row.
fn cell(text: &str) -> String {
    escape(text)
        .replace('|', "\\|")
        .replace("\n\n", "<br /><br />")
        .replace('\n', " ")
}

/// Hand-written framing for the overview page.
///
/// Kept in the generator rather than a checked-in partial so that the drift
/// check covers the entire rendered page, not just its tables.
const OVERVIEW: &str = r#"
Every command `tix` accepts, generated directly from the CLI's own argument
definition. If a flag exists, it is on this page.

## Notation

| Form | Meaning |
| --- | --- |
| `<VALUE>` | Required. |
| `[VALUE]` | Optional. |
| `<VALUE>...` | Repeatable — pass it more than once, or give several values. |

Every command also accepts `-h` / `--help`; `tix --version` prints the
version.

## Selecting a ticket

`tix ticket add`, `remove`, `info`, and `destroy` operate on one ticket. With
no flag they discover it by walking up from the working directory looking for
a `.tix/ticket.toml`, nearest ancestor winning. The walk follows the logical
working directory rather than resolving symlinks, and stops at a filesystem
boundary.

`--ticket` skips the walk, and its argument is read as one of two forms:

| You write | Read as | Resolves to |
| --- | --- | --- |
| `JIRA-123` | id | `tickets_directory/JIRA-123` |
| `./JIRA-123` | path | that directory, relative to the working directory |
| `../other`, `/abs/path`, `.` | path | that directory |

The rule is that a bare name is **always** an id. A ticket directory sitting
in your working directory must therefore be written `./JIRA-123`, not
`JIRA-123` — otherwise it resolves against the tickets directory instead.

Both forms are assertions, not starting points: pointing `--ticket` at a
subdirectory of a ticket is an error rather than a shorter walk.

`tix destroy` additionally takes the ticket as a positional argument, read
the same two ways — `tix destroy JIRA-123`. It conflicts with `--ticket`:
pass one or the other, not both.

## Plugins

Any argument `tix` does not recognise as a built-in command is dispatched to
a plugin: `tix deploy` execs `tix-deploy` from `PATH`, forwarding the
workspace context. Plugins are listed under their own heading in `tix --help`.
See the [plugin specification](https://github.com/armaan-v924/tix/blob/main/PLUGIN_SPEC.md)
for the contract.
"#;

/// Environment and exit-status notes, appended to the overview.
const ENVIRONMENT: &str = r#"
## Environment

| Variable | Effect |
| --- | --- |
| `TIX_CONFIG_PATH` | Location of the global config file. Beaten by `--config`; ignored when set but empty. |

With neither `--config` nor `TIX_CONFIG_PATH`, the config file is read from
the platform config directory — `~/.config/tix/config.toml` on Linux,
`~/Library/Application Support/tix/config.toml` on macOS. Every command
except `tix config init` and `tix cli completions` requires that file to
exist.

## Exit status

`tix` exits `0` on success and `1` on any error, printing `error: <message>`
to standard error. Diagnostics and log output also go to standard error, so
`tix ticket list --output json | jq` stays parseable regardless of log level.
"#;
